language: c
sudo: false

# Blacklist
branches:
  except:
    - gh-pages

env:
  global:
    - PRETTYNAME="Adafruit BME680 Arduino Library"
    - DOXYFILE=$TRAVIS_BUILD_DIR/Doxyfile

before_install:
   - source <(curl -SLs https://raw.githubusercontent.com/adafruit/travis-ci-arduino/master/install.sh)

install:
   - arduino --install-library "Adafruit Unified Sensor","Adafruit GFX Library","Adafruit SSD1306"

script:
   - build_main_platforms

# Generate and deploy documentation
after_success:
  - source <(curl -SLs  https://raw.githubusercontent.com/adafruit/travis-ci-arduino/master/library_check.sh)
  - source <(curl -SLs  https://raw.githubusercontent.com/adafruit/travis-ci-arduino/master/doxy_gen_and_deploy.sh)