
    // AUTO GENERATED FILE FROM version_increment.py, DO NOT EDIT THIS FILE
    #ifndef VERSION
      #define VERSION "5.9.36"
    #endif
    #ifndef BUILD_TIMESTAMP
      #define BUILD_TIMESTAMP "2020-04-11 21:25:11.963365"
    #endif
    