
    // AUTO GENERATED FILE FROM version_increment.py, DO NOT EDIT THIS FILE
    #ifndef VERSION
      #define VERSION "6.5.4"
    #endif
    #ifndef BUILD_TIMESTAMP
      #define BUILD_TIMESTAMP "2020-05-08 23:47:14.342266"
    #endif
    