
// AUTO GENERATED FILE FROM buildscript_versioning.py, DO NOT EDIT THIS FILE
#ifndef BUILD_NUMBER
  #define BUILD_NUMBER "6"
#endif
#ifndef VERSION
  #define VERSION "5.9.6 - 2020-04-03 13:04:08.190843"
#endif
#ifndef VERSION_SHORT
  #define VERSION_SHORT "5.9.6"
#endif
