name: GitHub Actions CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install platformio
        python --version
    - name: Install submodules 
      run: |        
        git submodule update --init
    - name: Setup template config files
      run: |                
        cp /home/runner/work/smart_thermostat/smart_thermostat/secrets.ini.template /home/runner/work/smart_thermostat/smart_thermostat/secrets.ini
    # - name: Setup tmate session
    #   uses: mxschmitt/action-tmate@v3
    - name: Static code analysis
      run: platformio check --verbose --severity=high --skip-packages            
    - name: Run PlatformIO (smartostat)
      run: platformio run -e smartostat
    - name: Creating smartostat artifact from BIN file 
      uses: actions/upload-artifact@v3
      with:
        name: firmware_build_artifact_smartostat.bin
        path: .pio/build/smartostat/firmware.bin
    - name: Run PlatformIO (smartoled)
      run: platformio run -e smartoled
    - name: Creating smartoled artifact from BIN file
      uses: actions/upload-artifact@v3
      with:
        name: firmware_build_artifact_smartoled.bin
        path: .pio/build/smartoled/firmware.bin
