name: GitHub Actions CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install platformio
        python --version
    - name: Install submodules 
      run: |        
        git submodule update --init
    - name: Set lib extra dirs for CI
      run: |     
        sed -i 's,^lib_extra_dirs =.*$,lib_extra_dirs = /home/runner/work/smart_thermostat/smart_thermostat/arduino_bootstrapper/arduino_bootstrapper,' platformio.ini
        cat platformio.ini
    - name: Setup template config files
      run: |                
        cp /home/runner/work/smart_thermostat/smart_thermostat/arduino_bootstrapper/include/Secrets.h.template /home/runner/work/smart_thermostat/smart_thermostat/include/Secrets.h
        cp /home/runner/work/smart_thermostat/smart_thermostat/arduino_bootstrapper/include/Secrets.h.template /home/runner/work/smart_thermostat/smart_thermostat/arduino_bootstrapper/include/Secrets.h   
        cp /home/runner/work/smart_thermostat/smart_thermostat/include/Configuration.h /home/runner/work/smart_thermostat/smart_thermostat/arduino_bootstrapper/include/Configuration.h
    # - name: Setup tmate session
    #   uses: mxschmitt/action-tmate@v2     
    - name: Static code analysis
      run: platformio check --verbose --severity=high --skip-packages            
    - name: Run PlatformIO (smartostat)
      run: platformio run -e smartostat
    - name: Creating smartostat artifact from BIN file 
      uses: actions/upload-artifact@v1
      with:
        name: firmware_build_artifact_smartostat.bin
        path: .pio/build/smartostat/firmware.bin
    - name: Run PlatformIO (smartoled)
      run: platformio run -e smartoled
    - name: Creating smartoled artifact from BIN file
      uses: actions/upload-artifact@v1
      with:
        name: firmware_build_artifact_smartoled.bin
        path: .pio/build/smartoled/firmware.bin
